"""Database creation

Revision ID: 0547ed24d302
Revises: 7243866da931
Create Date: 2024-09-03 02:12:54.763035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0547ed24d302'
down_revision: Union[str, None] = '7243866da931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering_events', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news_gathering_events', 'news_gathering', ['site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_gathering_events', type_='foreignkey')
    op.drop_column('news_gathering_events', 'site_id')
    # ### end Alembic commands ###
