"""Database creation

Revision ID: 07be8398964c
Revises: b8d8d5449798
Create Date: 2024-08-31 20:22:42.669383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07be8398964c'
down_revision: Union[str, None] = 'b8d8d5449798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering', sa.Column('parser_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'news_gathering', 'parsers', ['parser_id'], ['id'])
    op.drop_column('news_gathering', 'parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering', sa.Column('parser', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news_gathering', type_='foreignkey')
    op.drop_column('news_gathering', 'parser_id')
    # ### end Alembic commands ###
