"""Database creation

Revision ID: 1c6b4f733f0d
Revises: 0547ed24d302
Create Date: 2024-09-03 02:41:00.252700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6b4f733f0d'
down_revision: Union[str, None] = '0547ed24d302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering_events', sa.Column('event', sa.String(length=50), nullable=False))
    op.add_column('news_gathering_events', sa.Column('is_success', sa.Boolean(), nullable=False))
    op.add_column('news_gathering_events', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.drop_constraint('news_gathering_events_name_key', 'news_gathering_events', type_='unique')
    op.drop_constraint('news_gathering_events_value_key', 'news_gathering_events', type_='unique')
    op.drop_column('news_gathering_events', 'value')
    op.drop_column('news_gathering_events', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering_events', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('news_gathering_events', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('news_gathering_events_value_key', 'news_gathering_events', ['value'])
    op.create_unique_constraint('news_gathering_events_name_key', 'news_gathering_events', ['name'])
    op.drop_column('news_gathering_events', 'created_on')
    op.drop_column('news_gathering_events', 'is_success')
    op.drop_column('news_gathering_events', 'event')
    # ### end Alembic commands ###
