"""Database creation

Revision ID: 2ac037684ca1
Revises: ab07393e1bda
Create Date: 2024-09-03 07:54:01.049551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac037684ca1'
down_revision: Union[str, None] = 'ab07393e1bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('queue_output_news_package_name_key', 'queue_output_news_package', type_='unique')
    op.drop_constraint('queue_output_news_package_value_key', 'queue_output_news_package', type_='unique')
    op.drop_column('queue_output_news_package', 'value')
    op.drop_column('queue_output_news_package', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_output_news_package', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('queue_output_news_package', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('queue_output_news_package_value_key', 'queue_output_news_package', ['value'])
    op.create_unique_constraint('queue_output_news_package_name_key', 'queue_output_news_package', ['name'])
    # ### end Alembic commands ###
