"""Database add table

Revision ID: 3415b61e18b4
Revises: b616a065d047
Create Date: 2024-08-17 01:37:26.511463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3415b61e18b4'
down_revision: Union[str, None] = 'b616a065d047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('parser_type', sa.String(length=150), nullable=True))
    op.drop_column('parsers', 'type_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('type_parser', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('parsers', 'parser_type')
    # ### end Alembic commands ###
