"""Database creation

Revision ID: 3422ba9d66bb
Revises: 1c6b4f733f0d
Create Date: 2024-09-03 03:20:42.204664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3422ba9d66bb'
down_revision: Union[str, None] = '1c6b4f733f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering_malfunctions', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_constraint('news_gathering_malfunctions_grubber_event_id_fkey', 'news_gathering_malfunctions', type_='foreignkey')
    op.create_foreign_key(None, 'news_gathering_malfunctions', 'news_gathering_events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('news_gathering_malfunctions', 'grubber_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering_malfunctions', sa.Column('grubber_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news_gathering_malfunctions', type_='foreignkey')
    op.create_foreign_key('news_gathering_malfunctions_grubber_event_id_fkey', 'news_gathering_malfunctions', 'news_gathering_events', ['grubber_event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('news_gathering_malfunctions', 'event_id')
    # ### end Alembic commands ###
