"""Database creation

Revision ID: 3699009e2620
Revises: 3083fd64bd84
Create Date: 2024-08-29 13:05:22.243138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3699009e2620'
down_revision: Union[str, None] = '3083fd64bd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('is_parser_scheme_missing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsers', 'is_parser_scheme_missing')
    # ### end Alembic commands ###
