"""Database creation

Revision ID: 4c717a9d02c8
Revises: 88f2e588b3d0
Create Date: 2024-09-01 01:08:07.988289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c717a9d02c8'
down_revision: Union[str, None] = '88f2e588b3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_gathering', sa.Column('url', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_gathering', 'url')
    # ### end Alembic commands ###
