"""Database creation

Revision ID: 596db15a4078
Revises: 746c53a879ac
Create Date: 2024-09-05 17:41:02.039272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596db15a4078'
down_revision: Union[str, None] = '746c53a879ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internet_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_parsing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('crawl_events')
    op.drop_table('catalogs_gathering')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs_gathering',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], name='catalogs_gathering_parser_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='catalogs_gathering_pkey')
    )
    op.create_table('crawl_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crawl_events_pkey')
    )
    op.drop_table('catalog_parsing')
    op.drop_table('internet_sites')
    # ### end Alembic commands ###
