"""Database creation

Revision ID: 5b04709484d6
Revises: e40b43ee8393
Create Date: 2024-09-11 12:30:35.985767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b04709484d6'
down_revision: Union[str, None] = 'e40b43ee8393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internet_sites', sa.Column('catalog_gathering_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internet_sites', 'catalog_gathering', ['catalog_gathering_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internet_sites', type_='foreignkey')
    op.drop_column('internet_sites', 'catalog_gathering_id')
    # ### end Alembic commands ###
