"""Database creation

Revision ID: 5ff8f767033f
Revises: 
Create Date: 2024-09-13 18:10:21.114941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff8f767033f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes_parsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('parser_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parser_type', sa.String(length=150), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('is_parser_scheme_missing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_identifier', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('type_bot', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('update_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_identifier')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('second_name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_news_bot', sa.Boolean(), nullable=False),
    sa.Column('is_instruktor_bot', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('catalog_gathering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['schemes_parsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_gathering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('field_tags', sa.String(length=1024), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['schemes_parsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internet_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('news_gathering_id', sa.Integer(), nullable=True),
    sa.Column('catalog_gathering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_gathering_id'], ['catalog_gathering.id'], ),
    sa.ForeignKeyConstraint(['news_gathering_id'], ['news_gathering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_gathering_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['news_gathering.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_gathering_malfunctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('malfunction_type', sa.String(length=50), nullable=False),
    sa.Column('malfunction_details', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('text_error', sa.Text(), nullable=True),
    sa.Column('text_details', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('attribute_1', sa.Text(), nullable=True),
    sa.Column('attribute_2', sa.Text(), nullable=True),
    sa.Column('attribute_3', sa.Text(), nullable=True),
    sa.Column('attribute_4', sa.Text(), nullable=True),
    sa.Column('attribute_5', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_gathering_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_gathering_success',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_gathering_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grubber_event_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('more', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('main_tag', sa.String(length=255), nullable=True),
    sa.Column('field_tags', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=30), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grubber_event_id'], ['news_gathering_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_output_news_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['news_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_output_news_package')
    op.drop_table('news_posts')
    op.drop_table('news_gathering_success')
    op.drop_table('news_gathering_malfunctions')
    op.drop_table('news_gathering_events')
    op.drop_table('internet_sites')
    op.drop_table('news_gathering')
    op.drop_table('catalog_gathering')
    op.drop_table('users')
    op.drop_table('telegram_users')
    op.drop_table('settings')
    op.drop_table('schemes_parsers')
    op.drop_table('catalog_products')
    op.drop_table('catalog_categories')
    # ### end Alembic commands ###
