"""Database creation

Revision ID: 7243866da931
Revises: 43a1ba4d1480
Create Date: 2024-09-03 02:09:05.493238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7243866da931'
down_revision: Union[str, None] = '43a1ba4d1480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_gathering_malfunctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grubber_event_id', sa.Integer(), nullable=True),
    sa.Column('malfunction_type', sa.String(length=50), nullable=False),
    sa.Column('malfunction_details', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('text_error', sa.Text(), nullable=True),
    sa.Column('text_details', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('attribute_1', sa.Text(), nullable=True),
    sa.Column('attribute_2', sa.Text(), nullable=True),
    sa.Column('attribute_3', sa.Text(), nullable=True),
    sa.Column('attribute_4', sa.Text(), nullable=True),
    sa.Column('attribute_5', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grubber_event_id'], ['news_gathering_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_gathering_malfunctions')
    # ### end Alembic commands ###
