"""Database creation

Revision ID: 88f2e588b3d0
Revises: 199c4fa815ad
Create Date: 2024-08-31 21:12:11.836600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f2e588b3d0'
down_revision: Union[str, None] = '199c4fa815ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_gathering', 'parser_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_gathering', 'parser_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
