"""Database creation

Revision ID: a03b28fb4f90
Revises: 4c717a9d02c8
Create Date: 2024-09-01 19:09:38.450027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03b28fb4f90'
down_revision: Union[str, None] = '4c717a9d02c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs_gathering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogs_gathering')
    # ### end Alembic commands ###
