"""Database add table

Revision ID: b616a065d047
Revises: 065f960d229a
Create Date: 2024-08-17 00:32:27.048243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b616a065d047'
down_revision: Union[str, None] = '065f960d229a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_tag_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internet_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parser', sa.String(length=150), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parsers', sa.Column('parser_name', sa.String(length=255), nullable=False))
    op.drop_column('parsers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('parsers', 'parser_name')
    op.drop_table('vendors_tags')
    op.drop_table('internet_sites')
    op.drop_table('fields_tags')
    # ### end Alembic commands ###
