"""Database creation

Revision ID: b8d8d5449798
Revises: 3699009e2620
Create Date: 2024-08-31 17:51:22.774318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d8d5449798'
down_revision: Union[str, None] = '3699009e2620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_gathering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('field_tags', sa.String(length=1024), nullable=True),
    sa.Column('parser', sa.String(length=150), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scheduler')
    op.drop_table('internet_sites')
    op.drop_table('type_crawl_events')
    op.drop_table('periodic_tasks')
    op.alter_column('parsers', 'parser_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsers', 'parser_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('periodic_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='periodic_tasks_pkey')
    )
    op.create_table('type_crawl_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='type_crawl_events_pkey')
    )
    op.create_table('internet_sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parser', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='internet_sites_pkey')
    )
    op.create_table('scheduler',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scheduler_pkey')
    )
    op.drop_table('news_gathering')
    # ### end Alembic commands ###
