"""Database creation

Revision ID: e40b43ee8393
Revises: 66bb085f8f41
Create Date: 2024-09-11 12:27:24.979135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40b43ee8393'
down_revision: Union[str, None] = '66bb085f8f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('tg_bot', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('phone_number_tg', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('update_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_tg'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('catalog_gathering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('catalog_parsing')
    op.add_column('internet_sites', sa.Column('news_gathering_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internet_sites', 'news_gathering', ['news_gathering_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internet_sites', type_='foreignkey')
    op.drop_column('internet_sites', 'news_gathering_id')
    op.create_table('catalog_parsing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parser_id'], ['parsers.id'], name='catalog_parsing_parser_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='catalog_parsing_pkey')
    )
    op.drop_table('catalog_gathering')
    op.drop_table('tg_users')
    # ### end Alembic commands ###
