# System environment
system_name_news_bot: str = 'news_bot'
system_name_instruktor_bot: str = 'instruktor_bot'
system_catalog_parser_type: str = 'catalog_parser'
system_news_parser_type: str = 'news_parser'

params_name_queue_posts_status_send: str = 'send'
params_name_queue_posts_status_archive: str = 'archive'
params_name_news_formatting_min_len_title: str = 'news_formatting_min_len_title'
params_name_news_formatting_len_title: str = 'news_formatting_len_title'
params_name_news_formatting_min_len_details: str = 'news_formatting_min_len_details'
params_name_news_formatting_len_details: str = 'news_formatting_len_details'
params_name_news_main_tag: str = 'news_main_tag'
params_name_news_site_processing_timeout: str = 'news_site_processing_timeout'
params_name_news_number_of_days_to_view_sites: str = 'news_number_of_days_to_view_sites'
params_name_news_number_days_search_post: str = 'news_number_days_search_post'
params_name_news_post_matcher_ratio: str = 'news_post_matcher_ratio'
params_name_news_len_loaded_content: str = 'news_len_loaded_content'
params_name_news_bot_dispatch_min_time: str = 'news_bot_dispatch_min_time'
params_name_news_bot_dispatch_max_time: str = 'news_bot_dispatch_max_time'